### ISSUE TITLE
Celebrations by the months

### ISSUE THREAD

**Issue by olairmarcos** [iionly/celebrations#3]
Hello,
When you select the 'Celebrations by the months' option does not appear any member in the list of months. Display the reminder of upcoming celebrations after login does not work properly, not mosta birthdays notice in the coming days.
Tanks for help.

Excuse me. It is working properly. I was wrong setting the control panel plugin celebrations.
Great work.

**Comment by iionly** [comment]
So everything is working? If not, you could re-open the issue.
